# Generated by Django 2.0.6 on 2020-07-04 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.SmallIntegerField(choices=[(0, 'male'), (1, 'female')], default=0, max_length=80),
        ),
    ]
